name: CI • WDIO + Allure + Pages

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (.env.*)"
        type: choice
        default: prod
        options: [dev, staging, prod]
      browsers:
        description: "Which browser(s) to run"
        type: choice
        default: both
        options: [chrome, firefox, both]
      spec_path:
        description: "Optional: run single spec (e.g. test/specs/smoke.status.e2e.ts)"
        type: string
        required: false
      deploy:
        description: "Deploy Allure report to gh-pages?"
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build spec arg
        id: specarg
        run: |
          if [ -n "${{ inputs.spec_path }}" ]; then
            echo "SPEC_ARG=-- --spec ${{ inputs.spec_path }}" >> $GITHUB_ENV
          else
            echo "SPEC_ARG=" >> $GITHUB_ENV
          fi

      # Chrome
      - name: Run Chrome tests (${{ inputs.environment || 'prod' }})
        if: ${{ inputs.browsers == 'chrome' || inputs.browsers == 'both' || (github.event_name != 'workflow_dispatch') }}
        run: npm run test:${{ inputs.environment || 'prod' }}:chrome $SPEC_ARG
        env:
          CI: "true"

      # Firefox
      - name: Run Firefox tests (${{ inputs.environment || 'prod' }})
        if: ${{ inputs.browsers == 'firefox' || inputs.browsers == 'both' || (github.event_name != 'workflow_dispatch') }}
        run: npm run test:${{ inputs.environment || 'prod' }}:firefox $SPEC_ARG
        env:
          CI: "true"

      # Генеруємо звіт навіть якщо тести впали
      - name: Generate Allure report (always)
        if: always()
        run: |
          npm run report:allure:generate || true
          ls -lah || true
          ls -lah allure-results || true
          ls -lah allure-report || true

          # якщо раптом Allure не створив index.html — зробимо плейсхолдер, щоб не було 404
          if [ ! -f allure-report/index.html ]; then
            echo "No Allure results were produced. Creating placeholder index.html"
            mkdir -p allure-report
            printf '<!doctype html><meta charset="utf-8"><title>No report</title><h1>No Allure results were produced for this run.</h1>' > allure-report/index.html
          fi
          # відключаємо Jekyll, щоб не ламав структуру
          touch allure-report/.nojekyll

      - name: Upload Allure artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure to gh-pages
        if: >
          always() && (
            (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
            (github.event_name == 'workflow_dispatch' && inputs.deploy == 'true')
          )
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: allure-report
          clean: true
