name: CI • WDIO + Allure + Pages

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (.env.*)"
        type: choice
        default: prod
        options: [dev, staging, prod]
      browsers:
        description: "Which browser(s) to run"
        type: choice
        default: both
        options: [chrome, firefox, both]
      spec_path:
        description: "Optional: run single spec (e.g. test/specs/smoke.status.e2e.ts)"
        type: string
        required: false
      deploy:
        description: "Deploy Allure report to gh-pages?"
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  e2e:
    name: Run tests and publish Allure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # Підготуємо аргумент для одного файлу (якщо задано)
      - name: Build spec arg
        id: specarg
        run: |
          if [ -n "${{ inputs.spec_path }}" ]; then
            echo "SPEC_ARG=-- --spec ${{ inputs.spec_path }}" >> $GITHUB_ENV
          else
            echo "SPEC_ARG=" >> $GITHUB_ENV
          fi

      # Chrome
      - name: Run Chrome tests (${{ inputs.environment }})
        if: ${{ inputs.browsers == 'chrome' || inputs.browsers == 'both' || (github.event_name != 'workflow_dispatch' && true) }}
        run: npm run test:${{ inputs.environment || 'prod' }}:chrome $SPEC_ARG
        env:
          CI: "true"

      # Firefox
      - name: Run Firefox tests (${{ inputs.environment }})
        if: ${{ inputs.browsers == 'firefox' || inputs.browsers == 'both' || (github.event_name != 'workflow_dispatch' && true) }}
        run: npm run test:${{ inputs.environment || 'prod' }}:firefox $SPEC_ARG
        env:
          CI: "true"

      - name: Generate Allure report
        run: npm run report:allure:generate

      - name: Upload Allure artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure to gh-pages
        # Автодеплой для push у main І для ручного запуску з прапорцем deploy=true
        if: >
          (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
          (github.event_name == 'workflow_dispatch' && inputs.deploy == 'true')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: allure-report
